NUMBER_OF_SIMULATION_DAY = 1
N_OF_EC = 1
SIM_DEBUG = True
AVERAGE_GIVEN_DATA = True
REINFORCEMENT_ONLINE = False
REWARD_WINDOW_SIZE = 1
NUMBER_OF_EPISODES_CONF = 100000
SHOW_EVERY_CONF = 10000

method_list_rl = ["DQN"]
print("CONFIGURATION FILE::{}\t AVG:{}".format(__file__, AVERAGE_GIVEN_DATA), flush=True)
