DEBUGGING_ALLOW = False
AVERAGE_GIVEN_DATA = False
REINFORCEMENT_ONLINE = False
NUMBER_OF_EPISODES_CONF = 2000
SHOW_EVERY_CONF = 200
SOLAR_PANEL_INSTANCE_SIZE_CONF = 1
BATTERY_INSTANCE_SIZE_CONF = 1
LEARNING_RATE_SIZE_CONF = 1
DISCOUNT_SIZE_CONF = 1
city_name_list = ['jakarta']
traffic_rate_list = [1]
method_list_rl = ["Q"]

REWARD_WINDOW_SIZE = 48
print("CONFIGURATION FILE::{}\t AVG:{}".format(__file__, AVERAGE_GIVEN_DATA), flush=True)
