SIM_DEBUG = True
AVERAGE_GIVEN_DATA = False
REINFORCEMENT_ONLINE = True
NUMBER_OF_EPISODES_CONF = 4000
SHOW_EVERY_CONF = 500
SOLAR_PANEL_BASE_CONF = 0.1
BATTERY_BASE_CONF = 100
SOLAR_PANEL_INSTANCE_SIZE_CONF = 1
BATTERY_INSTANCE_SIZE_CONF = 1
LEARNING_RATE_SIZE_CONF = 1
DISCOUNT_SIZE_CONF = 1
# city_name_list = ['istanbul']
# traffic_rate_list = [2]
city_name_list = ['stockholm', 'cairo', 'jakarta', 'istanbul']
traffic_rate_list = [1, 2, 3]
method_list_rl = ["Q", "S"]
# method_list_rl = []
method_list_static = ["CRAN", "DRAN"]
# method_list_static = []
REWARD_WINDOW_SIZE = 48
print("CONFIGURATION FILE::{}\t AVG:{}".format(__file__, AVERAGE_GIVEN_DATA), flush=True)
