SIM_DEBUG = True
AVERAGE_GIVEN_DATA = False
REINFORCEMENT_ONLINE = True
N_OF_EC = 5
# NUMBER_OF_EPISODES_CONF = 4000
# SHOW_EVERY_CONF = 500
# SOLAR_PANEL_BASE_CONF = 0.05
# BATTERY_BASE_CONF = 50
# SOLAR_PANEL_INSTANCE_SIZE_CONF = 4
# BATTERY_INSTANCE_SIZE_CONF = 4
# LEARNING_RATE_SIZE_CONF = 1
# DISCOUNT_SIZE_CONF = 1
# city_name_list = ['istanbul']
# traffic_rate_list = [1]
method_list_rl = []
# method_list_rl = ["Q"]
# method_list_static = []
method_list_milp = []

print("CONFIGURATION FILE::{}\t AVG:{}".format(__file__, AVERAGE_GIVEN_DATA), flush=True)
